quarkus.http.port=8080
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
mp.openapi.extensions.smallrye.info.title=LottoMax Enterprise API
mp.openapi.extensions.smallrye.info.version=1.0.0
